### PR TITLE
Update guitartuner-core.js

### PR DESCRIPTION
**Pull request by DmitryOlkhovoi**

### CODE REVIEW

**Comment by addyosmani** [comment]
PRs should probably include a description as to why this change is necessary :)

**Comment by DmitryOlkhovoi** [comment]
I just think this method more suitable for this. All we need it's iterate elements of array, don't change them. So, maybe i don't know hipsters methods, but it's seems like a wrong way of using map.

**Comment by AndrewBroz** [comment]
Dima is correct. Unless the returned array is being used, `forEach` is more idiomatic than `map`.

**Comment by beaufortfrancois** [comment]
@addyosmani What do you think?

**Pull request merged**
